# Generated by Django 5.1.4 on 2025-01-07 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_App', '0002_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date',
            new_name='task_date',
        ),
    ]
