# Generated by Django 5.1.4 on 2025-01-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_App', '0003_rename_date_task_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
